### PR TITLE
Create option to cut to top 3

### LINKED ISSUE #67: Enable Top 3 Cut
Implement a Top 3 Cut.
Which is: 3rd of Swiss playes against 2nd. 2nd has choice of side. Winner plays against 1st. 1st has choice of side.

### PR DESCRIPTION
**Pull request by shdblowers**
This is to fix #67 

This is my first time contributing to this repo and my first time writing Ruby/Rails, so please forgive any obvious mistakes.

I wanted to pick up a feature that was fairly straight-forward. Though this issue does have a few interesting considerations...

Firstly, the Cut to Top X buttons are getting a little busy now, though given that it is hardcoded for each number it would be difficult to implement it to cut to any arbitrary number.
image

Secondly, the Top 3 bracket I've made has been put under "Double Elimination" options, though it isn't double elim, I wasn't really sure how to get around that issue as it seems like double elim is the only strategy for the cut.

Anyway, look forward to feedback and hope this PR is useful.

### CODE REVIEW

**Review by haradan — APPROVED** [review]

**Comment by haradan** [comment]
I noticed the sides are pre-selected so that the player who won the first round plays the side they haven't played yet in the first round. That's not correct, but it might not be a big problem.

**Review by haradan — CHANGES_REQUESTED** [review]
I've looked into it a bit more. It should be 3 games of double-elimination, where the 2nd and 3rd seed count as having already lost a game. That means the 1st seed will win unless one of the others can win 3 games in a row.

I think if you add the third game in it's not a big deal that it pre-chooses the sides for game 2.

**Comment by haradan** [comment]
I'll figure out which way we need it to work and update here.

**Review by haradan — APPROVED** [review]
Apologies, it looks like it's correct as is. The Organized Play Policies document has it as an option for asynchronous events, and it says "single elimination, with higher seed choosing the first deck (and alternating decks after that)".

**Comment by haradan** [comment]
I think I might have misunderstood the OP document, it looks like it's talking about best of 3 there. This is fine as it is though.

**Comment by shdblowers** [comment]
Awesome stuff, thanks for the merge

**Pull request merged**
